language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get install liblapack-dev gfortran python-scipy libblas-dev libsuitesparse-dev swig
  
install:
  - pip install numpy
  - pip install nose
  - python setup.py install
script:  nosetests
